replicaCount: 1
image:
  repository: ghcr.io/drivershub/placeholder
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources: {}
env: []
postgres:
  enabled: false
redis:
  enabled: false
kafka:
  enabled: false
